http:
  port: "8089"
  
sfdc:
  username: "![eSJYxbIXhIDC6MfS9Ioq7BMJ7/W1PWBPUbB5TAaWjrek4+4l5deIlg==]"
  password: "![/GQYxncq3Yf2UjaKDtAFEA==]"
  token: "![Tg2XIiMj2ZE6utuARNJFwrA7atoVm2jFSCfDtYldnII=]"
  
file:
  accountsDir: "C:/Users/atorh/Downloads/DEX401-files5/CDEV-DEX401-EN-07Jun2024-Student-Files_SP/resources"
  
db:
  host: "mudb.mule-training.com"
  port: "3306"
  user: "JcUbNrpRaf0="
  password: "JcUbNrpRaf0="
  database: "/vZNMVMTTV9pc+0kWSq+Bw=="